# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/kevinchen/Desktop/POGUpdator/POGUpdatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

def setupUILayout(self,MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(1000, 600)

    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")

    self.refreshGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.refreshGroupBox.setTitle("Refresh:")
    self.refreshVBox = QtWidgets.QVBoxLayout()
    self.refreshGroupBox.setLayout(self.refreshVBox)


    self.facingGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.facingGroupBox.setTitle("Facings:")
    self.facingVBox = QtWidgets.QVBoxLayout()
    self.facingGroupBox.setLayout(self.facingVBox)

    self.shelfGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.shelfGroupBox.setTitle("Shelves:")
    self.shelfVBox = QtWidgets.QVBoxLayout()
    self.shelfGroupBox.setLayout(self.shelfVBox)
    
    self.updateGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.updateGroupBox.setTitle("Update:")
    self.updateVBox = QtWidgets.QVBoxLayout()
    self.updateGroupBox.setLayout(self.updateVBox)

    self.exitGroupBox = QtWidgets.QGroupBox( self.centralwidget)
    self.exitGroupBox.setTitle("Quit:")
    self.exitVBox = QtWidgets.QVBoxLayout()
    self.exitGroupBox.setLayout(self.exitVBox)



    self.pushButton_refreshing = QtWidgets.QPushButton(self.centralwidget,clicked=self.refreshPOG)
    self.pushButton_refreshing.setObjectName("pushButton_refreshing")
    self.pushButton_refreshing.setStyleSheet('QPushButton {background-color: #A3C1DA; color: green;}')


    self.pushButton_updatePOG = QtWidgets.QPushButton(self.centralwidget,clicked=self.updatePOG)
    self.pushButton_updatePOG.setObjectName("pushButton_updatePOG")
    self.pushButton_updatePOG.setStyleSheet('QPushButton {background-color: #A3C1DA; color: red;}')

    self.pushButton_addFacing = QtWidgets.QPushButton(self.centralwidget,clicked=self.onPushButtonAddFacing)
    self.pushButton_addFacing.setObjectName("pushButton_addFacing")
    self.pushButton_addFacing.setStyleSheet('QPushButton {background-color: #A3C1DA; color: black;}')

    self.pushButton_deleteFacing = QtWidgets.QPushButton(self.centralwidget,clicked=self.onPushButtonDeleteFacing)
    self.pushButton_deleteFacing.setObjectName("pushButton_deleteFacing")
    self.pushButton_deleteFacing.setStyleSheet('QPushButton {background-color: #A3C1DA; color: black;}')

    self.pushButton_addShelf = QtWidgets.QPushButton(self.centralwidget,clicked=self.onPushButtonAddShelf)
    self.pushButton_addShelf.setObjectName("pushButton_addShelf")
    self.pushButton_addShelf.setStyleSheet('QPushButton {background-color: black; color: #A3C1DA;}')
    self.pushButton_deleteShelf = QtWidgets.QPushButton(self.centralwidget,clicked=self.onPushButtonDeleteShelf)
    self.pushButton_deleteShelf.setObjectName("pushButton_deleteShelf")
    self.pushButton_deleteShelf.setStyleSheet('QPushButton {background-color: black; color: #A3C1DA;}')
    self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget,clicked=self.exitApp)
    self.pushButton_exit.setObjectName("pushButton_exit")
    self.pushButton_exit.setStyleSheet('QPushButton {background-color: yellow; color: red;}')
    spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    

    self.noticeLabel = QtWidgets.QLabel(self.centralwidget)

    self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
    self.tableWidget.setObjectName("tableWidget")
    self.tableWidget.cellClicked.connect(self.onTableCellClicked)
    self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
    self.tableWidget.setColumnCount(0)
    self.tableWidget.setRowCount(0)

#  create layout
    self.gridLayout_windowArea = QtWidgets.QGridLayout(self.centralwidget)
    self.gridLayout_windowArea.setObjectName("gridLayout_windowArea")

    self.gridLayout_buttonArea = QtWidgets.QGridLayout()
    self.gridLayout_buttonArea.setObjectName("gridLayout_buttonArea")

    self.gridLayout_GroupBoxArea = QtWidgets.QGridLayout()
    self.gridLayout_GroupBoxArea.setObjectName("gridLayout_GroupBoxArea")

    self.gridLayout_tableArea = QtWidgets.QGridLayout()
    self.gridLayout_tableArea.setObjectName("gridLayout_tableArea")
# add layout item

    self.gridLayout_GroupBoxArea.addWidget(self.refreshGroupBox,0,0,1,1)
    self.gridLayout_GroupBoxArea.addWidget(self.facingGroupBox,2,0,1,1)
    self.gridLayout_GroupBoxArea.addWidget(self.shelfGroupBox,3,0,1,1)
    self.gridLayout_GroupBoxArea.addWidget(self.updateGroupBox,4,0,1,1)
    self.gridLayout_GroupBoxArea.addWidget(self.exitGroupBox,6,0,1,1)
    

    self.refreshVBox.addWidget(self.pushButton_refreshing)
    self.facingVBox.addWidget(self.pushButton_addFacing)
    self.facingVBox.addWidget(self.pushButton_deleteFacing)
    self.shelfVBox.addWidget(self.pushButton_addShelf)
    self.shelfVBox.addWidget(self.pushButton_deleteShelf)
    self.updateVBox.addWidget(self.pushButton_updatePOG)
    self.exitVBox.addWidget(self.pushButton_exit)

    # self.gridLayout_buttonArea.addWidget(self.pushButton_addFacing, 1, 1, 1, 1)
    # self.gridLayout_buttonArea.addWidget(self.pushButton_deleteFacing, 3, 1, 1, 1)

    # self.gridLayout_buttonArea.addWidget(self.pushButton_addShelf, 6, 1, 1, 1)
    # self.gridLayout_buttonArea.addWidget(self.pushButton_deleteShelf,8, 1, 1, 1)
    
    # self.gridLayout_buttonArea.addWidget(self.pushButton_updatePOG, 3, 0, 1, 1)
    # self.gridLayout_buttonArea.addWidget(self.pushButton_exit, 4, 0, 1, 1)

    # self.gridLayout_buttonArea.addItem(spacerItem, 2, 0, 1, 1)
    self.gridLayout_GroupBoxArea.addItem(spacerItem, 1, 0, 1, 1)
    self.gridLayout_GroupBoxArea.addItem(spacerItem, 5, 0, 1, 1)
    # self.gridLayout_GroupBoxArea.addItem(spacerItem, 5, 0, 1, 1)
    # self.gridLayout_buttonArea.addItem(spacerItem, 3, 0, 1, 1)
    # self.gridLayout_buttonArea.addItem(spacerItem, 9, 0, 1, 1)
    # self.gridLayout_buttonArea.addItem(spacerItem, 11, 0, 1, 1)

    self.gridLayout_tableArea.addWidget(self.tableWidget, 1, 2, 1, 1)
    self.gridLayout_tableArea.addWidget(self.noticeLabel, 0, 2, 1, 1)
    self.gridLayout_windowArea.addLayout(self.gridLayout_tableArea, 0, 1, 1, 1)
    self.gridLayout_windowArea.addLayout(self.gridLayout_buttonArea, 0, 0, 1, 1)

    self.gridLayout_buttonArea.addLayout(self.gridLayout_GroupBoxArea,0,0,1,1)


    MainWindow.setCentralWidget(self.centralwidget)
    # self.statusbar = QtWidgets.QStatusBar(MainWindow)
    # self.statusbar.setObjectName("statusbar")
    # MainWindow.setStatusBar(self.statusbar)

    retranslateUi(self,MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "Sungal Corp POG Updater Utility"))
    self.pushButton_refreshing.setText(_translate("MainWindow", "Restore"))
    self.pushButton_updatePOG.setText(_translate("MainWindow", "Update POG"))
    self.pushButton_addShelf.setText(_translate("MainWindow", "Add Shelf"))
    self.pushButton_addFacing.setText(_translate("MainWindow", "Add Facing"))
    self.pushButton_deleteFacing.setText(_translate("MainWindow", "Delete Facing"))
    self.pushButton_deleteShelf.setText(_translate("MainWindow", "Delete Shelf"))
    self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
    self.noticeLabel.setText(_translate("MainWindow", "Please select POG Item from table below"))



